### ISSUE TITLE
Custom PETSc Build with Apple Acceleration Framework

### ISSUE THREAD

**Issue by BrushXue** [gerlero/homebrew-openfoam#81]
Currently homebrew PETSc is built with `openblas` and `scalapack`. There's potential performance boost if you can make a tap building PETSc with Apple's proprietary [BLAS](https://developer.apple.com/documentation/accelerate/blas) and [LAPACK](https://developer.apple.com/documentation/accelerate/solving_systems_of_linear_equations_with_lapack). Then you can compare the performance between OpenFOAM's own matrix solver, default PETSc and PETSc with Accelerate Framework.
My viscoelastic flow solver uses `Eigen` which can do the same test. If the benchmark case is more than 20% faster, are you interested in collaborating a conference paper?

**Comment by BrushXue** [comment]
The Acceleration Framework variant is already in https://ports.macports.org/port/petsc/details/ so should be easy to make a homebrew replica.

**Comment by gerlero** [comment]
I'm not a user of PETSc (even though I know a few people who use it). I think I could help out in testing a new formula. Feel free to shoot me an email.

**Comment by BrushXue** [comment]
I would test the macports build first. If it does work I'll update.

People already tested PETScFoam a lot. For me, sometimes I can get 10% faster, sometimes same speed. It really depends. I'm curious what happens if I can utilized the [matrix coprocessor](https://medium.com/swlh/apples-m1-secret-coprocessor-6599492fc1e1) on M1.

**Comment by BrushXue** [comment]
Seems like homebrew `petsc` is also calling accelerate framework, although I didn't find any relative flags being used. So this could be closed.

**Comment by BrushXue** [comment]
Didn’t find related flags in source code/homebrew. But when the solver crashes, the error message has something from Metal Framework which means Apple proprietary library is linked.

**Comment by gerlero** [comment]
Oh, interesting.
